import Head from 'next/head'
import Navigations from '../components/Navigations'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oppgave.9 - Next.js og API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Oppgave.9
        </h1>

        <div className={styles.grid}>
          <Navigations />
        </div>
      </main>

      <footer className={styles.footer}>
        <p>http://localhost:3000/api/peoples</p>
      </footer>
    </div>
  )
}
